// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Project struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdateAt  time.Time
	Name      string
	Images    []string
	Ocrdata   pqtype.NullRawMessage
}

type Task struct {
	ID        uuid.UUID
	Title     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
